stages:
  - test

image: golang

testing:
  stage: test
  script:
    - sudo apt install protobuf-compiler
    - make tools
    - make compile-protobuf
    - go get ./...
    - go mod vendor
    - make test

