image: docker:stable

stages:
  - test
  - build

services:
  - docker:dind

variables:
  TAG: ${CI_COMMIT_SHORT_SHA}
  CONTAINER_NAME: ${REGISTRY}/love_plus/data-ingest

run test:
  stage: test
  image: golang:latest
  script:
    - go test -v ./...

.docker_login:
  before_script:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ${REGISTRY}

build dev:
  stage: build
  extends: .docker_login
  script:
    - docker build -t ${CONTAINER_NAME}:${TAG} --build-arg env=local .
    - echo pushing ${CONTAINER_NAME}:${TAG}
    - docker push ${CONTAINER_NAME}:${TAG}
  only:
    - develop


build prod:
  stage: build
  extends: .docker_login
  script:
    - docker build -t ${CONTAINER_NAME}:${CI_COMMIT_TAG} --build-arg env=prod .
    - echo pushing ${CONTAINER_NAME}:${CI_COMMIT_TAG}
    - docker push ${CONTAINER_NAME}:${CI_COMMIT_TAG}
  only:
    - tags

