stages:
  - test

image: golang

testing:
  stage: test
  script:
    - apk add --no-cache protobuf
    - make tools
    - make compile-protobuf
    - go get ./...
    - go mod vendor
    - make test

