apiVersion: v1
kind: Service
metadata:
  name: grpcgw
spec:
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
  selector:
    app: grpcgw
  type: NodePort
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: grpcgw
spec:
  selector:
    matchLabels:
      app: grpcgw
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grpcgw
    spec:
      containers:
      - image: grpcgw-eg
        imagePullPolicy: Never
        name: grpcgw
        env:
        - name: DB_CONNECTION_STRING
          value: root:9LcVncRj8c@tcp(10.101.84.118:3306)/test?charset=utf8
        - name: ENVIRONMENT
          value: stage
        ports:
        - containerPort: 8080
          containerPort: 8081
          name: grpcgw
