apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-core
spec:
  ports:
    - port: {{ .Values.service.internal.restPort }}
      nodePort: {{ .Values.service.external.restPort }}
      targetPort: {{ .Values.deployment.restPort }}
      protocol: TCP
      name: {{ .Release.Name }}-rest-port
    - port: {{ .Values.service.internal.grpcPort }}
      nodePort: {{ .Values.service.external.grpcPort }} 
      targetPort: {{ .Values.deployment.grpcPort }}
      protocol: TCP
      name: {{ .Release.Name }}-grpc-port
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Release.Name }}-core
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app:  {{ .Release.Name }}
    spec:
      containers:
      - image:  {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Release.Name }}
        env:
        - name: DB_CONNECTION_STRING
          value: root:41XD344KDt@tcp(mean-crab-mysql.default.svc.cluster.local:3306)/test?charset=utf8 #manually get this
        - name: ENVIRONMENT
          value: stage
        ports:
          - containerPort: {{ .Values.deployment.restPort }}
          - containerPort: {{ .Values.deployment.grpcPort }}
