CREATE TABLE IF NOT EXISTS `pet` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(30) NOT NULL,
    `owner` VARCHAR(30) NOT NULL,
    `species` VARCHAR(30) NOT NULL,
    `sex` CHAR(1) NOT NULL,
    `birth` DATE NOT NULL,
    `death` DATE DEFAULT NULL,
    `created` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `updated` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (`id`)
);


