// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/util.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponsePayload struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Detail               string   `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponsePayload) Reset()         { *m = ResponsePayload{} }
func (m *ResponsePayload) String() string { return proto.CompactTextString(m) }
func (*ResponsePayload) ProtoMessage()    {}
func (*ResponsePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ee2dabd6e5ccfb4, []int{0}
}

func (m *ResponsePayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponsePayload.Unmarshal(m, b)
}
func (m *ResponsePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponsePayload.Marshal(b, m, deterministic)
}
func (m *ResponsePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponsePayload.Merge(m, src)
}
func (m *ResponsePayload) XXX_Size() int {
	return xxx_messageInfo_ResponsePayload.Size(m)
}
func (m *ResponsePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponsePayload.DiscardUnknown(m)
}

var xxx_messageInfo_ResponsePayload proto.InternalMessageInfo

func (m *ResponsePayload) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResponsePayload) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ResponsePayload) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterType((*ResponsePayload)(nil), "proto.ResponsePayload")
}

func init() { proto.RegisterFile("proto/util.proto", fileDescriptor_9ee2dabd6e5ccfb4) }

var fileDescriptor_9ee2dabd6e5ccfb4 = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2d, 0xc9, 0xcc, 0xd1, 0x03, 0x33, 0x85, 0x58, 0xc1, 0x94, 0x52, 0x24, 0x17,
	0x7f, 0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x6a, 0x40, 0x62, 0x65, 0x4e, 0x7e, 0x62, 0x8a,
	0x90, 0x04, 0x17, 0x7b, 0x71, 0x69, 0x72, 0x72, 0x6a, 0x71, 0xb1, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0x47, 0x10, 0x8c, 0x2b, 0x24, 0xc2, 0xc5, 0x9a, 0x5a, 0x54, 0x94, 0x5f, 0x24, 0xc1, 0xa4, 0xc0,
	0xa8, 0xc1, 0x19, 0x04, 0xe1, 0x08, 0x89, 0x71, 0xb1, 0xa5, 0xa4, 0x96, 0x24, 0x66, 0xe6, 0x48,
	0x30, 0x83, 0x85, 0xa1, 0xbc, 0x24, 0x36, 0xb0, 0x0d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x73, 0x8f, 0x6e, 0xc3, 0x7c, 0x00, 0x00, 0x00,
}
